version: 0.1
env:
  secrets-manager:
    AWS_ACCESS_KEY_ID: "build/eks:eks_access_key_id"
    AWS_SECRET_ACCESS_KEY: "build/eks:eks_secret_access_key"
    ALF_PRIVATE_REPO_USR: "build/eks:alf_private_repo_usr"
    ALF_PRIVATE_REPO_PWD: "build/eks:alf_private_repo_pwd"
    AWS_CODEART_DOMAIN: "iikt"
  variables:
    IMAGE_TAG: "7.2.0.2-0.233"
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
