apiVersion: v2
appVersion: 23.4.0
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.1.4
- condition: postgresql.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.8.5
- alias: postgresql-sync
  condition: postgresql-sync.enabled
  name: postgresql
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.8.5
- alias: alfresco-control-center
  condition: alfresco-control-center.enabled
  name: alfresco-adf-app
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 0.2.0
- alias: alfresco-digital-workspace
  condition: alfresco-digital-workspace.enabled
  name: alfresco-adf-app
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 0.2.0
- name: alfresco-repository
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 0.8.0
- condition: activemq.enabled
  name: activemq
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.6.0
- condition: alfresco-transform-service.enabled
  name: alfresco-transform-service
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 2.1.2
- alias: alfresco-search
  condition: alfresco-search.enabled
  name: alfresco-search-service
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 4.0.0
- condition: alfresco-sync-service.enabled
  name: alfresco-sync-service
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 6.1.0
- condition: alfresco-search-enterprise.enabled
  name: alfresco-search-enterprise
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 4.2.0
- condition: alfresco-connector-msteams.enabled
  name: alfresco-connector-msteams
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 1.2.0
- alias: share
  condition: share.enabled
  name: alfresco-share
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 1.2.0
- condition: alfresco-connector-ms365.enabled
  name: alfresco-connector-ms365
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 2.2.0
- condition: alfresco-ai-transformer.enabled
  name: alfresco-ai-transformer
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.0.0
- condition: elasticsearch.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.17.3
- alias: elasticsearch-audit
  condition: elasticsearch-audit.enabled
  name: elasticsearch
  repository: https://helm.elastic.co
  version: 7.17.3
- alias: kibana-audit
  condition: kibana-audit.enabled
  name: kibana
  repository: https://helm.elastic.co
  version: 7.17.3
- condition: alfresco-audit-storage.enabled
  name: alfresco-audit-storage
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 0.1.0
description: A Helm chart for deploying Alfresco Content Services
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- content
- content services
- alfresco
- alfresco content services
name: alfresco-content-services
sources:
- https://github.com/Alfresco/acs-deployment
version: 8.6.1
