apiVersion: v2
appVersion: 2.0.4
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.1.4
description: A Helm chart for deploying Alfresco connector msteams service
name: alfresco-connector-msteams
type: application
version: 1.2.0
