apiVersion: v2
appVersion: 4.2.0
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.1.4
- name: activemq
  repository: https://alfresco.github.io/alfresco-helm-charts/
  tags:
  - ci
  version: 3.6.0
- name: elasticsearch
  repository: https://helm.elastic.co
  tags:
  - ci
  version: 7.17.3
description: A Helm chart for deploying Alfresco Elasticsearch connector
name: alfresco-search-enterprise
type: application
version: 4.2.0
