apiVersion: v1
kind: PersistentVolume
metadata:
  name: alf-content-pv-${NAMESPACE}
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: alfresco-efs-sc
  nfs:
    server: ${EFSDNS}
    path: "/"
