apiVersion: v1
kind: PersistentVolume
metadata:
  name: alf-content-pv-${EFS_PV_NAME}
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: alfresco-efs-sc-${EFS_PV_NAME}
  nfs:
    server: ${EFS_DNS_NAME}
    path: "/"
