apiVersion: v1
kind: PersistentVolume
metadata:
  name: alf-content-pv
  namespace: ${NAMESPACE}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: alfresco-efs-sc
  nfs:
    server: ${EFS_DNS_NAME}
    path: "/"
