apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: alfresco-efs-sc
  namespace: ${NAMESPACE}
provisioner: efs.csi.aws.com
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer