kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alf-content-pvc-${NAMESPACE}
  namespace: ${NAMESPACE}
spec:
  storageClassName: alfresco-efs-sc
  volumeName: alf-content-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
