kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: alf-content-pvc-${EFS_PV_NAME}
  namespace: ${NAMESPACE}
spec:
  storageClassName: alfresco-efs-sc-${EFS_PV_NAME}
  volumeName: alf-content-pv-${EFS_PV_NAME}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
