apiVersion: v1
kind: Pod
metadata:
  name: ebs-test-pod
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["sh", "-c", "echo 'hello world' && sleep 3600"]
    volumeMounts:
    - name: test-volume
      mountPath: /mnt/ebs
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: ebs-test-pvc
