apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: acs:psp
  namespace: ${NAMESPACE}
rules:
- apiGroups:
  - policy
  resourceNames:
  - kube-system
  resources:
  - podsecuritypolicies
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acs:psp:default
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acs:psp
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${NAMESPACE}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: acs:psp:acs-ingress
  namespace: ${NAMESPACE}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: acs:psp
subjects:
- kind: ServiceAccount
  name: acs-ingress
  namespace: ${NAMESPACE}