apiVersion: v2
appVersion: 2.0.13
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.1.4
description: A Helm chart for deploying Alfresco Insight Zeppelin
home: https://www.alfresco.com
icon: https://avatars0.githubusercontent.com/u/391127?s=200&v=4
keywords:
- zeppelin
- insight zeppelin
- alfresco zeppelin
- alfresco insight zeppelin
name: alfresco-insight-zeppelin
sources:
- https://github.com/Alfresco/alfresco-helm-charts
version: 3.0.4
