apiVersion: v2
appVersion: 4.1.5
dependencies:
- name: alfresco-common
  repository: https://alfresco.github.io/alfresco-helm-charts/
  version: 3.1.4
- name: activemq
  repository: https://alfresco.github.io/alfresco-helm-charts/
  tags:
  - ci
  version: 3.6.0
description: A Helm chart for deploying Alfresco Transform Services
name: alfresco-transform-service
type: application
version: 2.1.2
